### PR TITLE
Adding the Toqito project to README.md.

### PR DESCRIPTION
**Pull request by vprusso**

### CODE REVIEW

**Comment by markf94** [comment]
Hi @vprusso! Thanks for this PR and great work on Toqito! I'm more than happy to add it to the list. However, I would not classify it as a Quantum full-stack library but either under `Quantum algorithms` or `Quantum tools`. Which one do you prefer? Please add it to one of the two categories and I'll merge the PR!

**Comment by vprusso** [comment]
Hi @markf94. Thanks for your kind words, and for your response as well! And you're quite right to categorize it under something else as a more appropriate heading. I think `Quantum tools` is probably the more correct category. I'll update my pull request accordingly. Thanks for the feedback!

**Comment by vprusso** [comment]
The category has been updated accordingly. Let me know if I can address anything else, and thanks again.

**Comment by markf94** [comment]
Thanks @vprusso! Merged :)

**Pull request merged**
