### PR TITLE
Add Munich Quantum Toolkit packages

### PR DESCRIPTION
**Pull request by flowerthrower**

### CODE REVIEW

**Comment by dlyongemallo** [comment]
Hi, @flowerthrower. Thanks for the contribution! I see that this PR is still marked as "draft". Is it ready for review? 

(I don't know how this was missed. I knew about the MQT but I guess I assumed it was already listed.)

**Comment by flowerthrower** [comment]
Hi @dlyongemallo,
I wanted one of the main MQT contributers to have a quick look at these descriptions before marking the PR ready. @burgholzer assured me this will be done soon.
Anyway, thank you for the reminder!

**Comment by burgholzer** [comment]
I'll have a look through the PR either today or tomorrow 😌👍🏻

**Comment by dlyongemallo** [comment]
What's the status now?

**Comment by burgholzer** [comment]
> What's the status now?

Ready to merge from our side 😃

**Comment by burgholzer** [comment]
> What's the status now?

Ready to merge from our side 😃

**Comment by dlyongemallo** [comment]
Merged. Thanks for the contribution @flowerthrower @burgholzer!

**Pull request merged**
