### PR TITLE
Added Tangelo and Tangelo examples to the repository list

### PR DESCRIPTION
**Pull request by ValentinS4t1qbit**
Howdy !

Added [Tangelo](https://github.com/goodchemistryco/Tangelo) and [Tangelo-Examples](https://github.com/goodchemistryco/Tangelo-Examples/) to the README under **quantum algorithms**. 

I wonder if Tangelo qualifies for other categories too. Although Tangelo is a collection of building blocks and algorithms for the simulation of quantum chemistry workflows on quantum computers, some of its contents are not necessarily related to chemistry and can be used as simple imports.

- It supports users in designing and carrying hardware experiments (connections to QPUs, manipulation of Histograms, reduction of resources...)
- It offers functions allowing to connect various quantum projects together (Qulacs, Qiskit, Cirq, Q#, Pennylane, ...) and convenient high-level abstractions to several simulators (including an original symbolic simulator in sympy).

Could it qualify as full-stack as well ? Some users have been relying on it for non-chemistry applications.

### CODE REVIEW

**Comment by dlyongemallo** [comment]
What do you think is the best category? We try not to add the same package to multiple categories if there's a best fit, as otherwise the list would become messy and confusing as there are many packages which could arguably belong to multiple categories.

**Comment by ValentinS4t1qbit** [comment]
I think the best category is full stack, since we provide an algorithm library, our own simulators, and other tools as well to explore circuits or submit them to various hardware. I have reflected this in the change, and are no longer listed under quantum-algorithms :)

**Comment by dlyongemallo** [comment]
Can you combine the entries into one line (see the example of `gdsfactory`)? Thanks.

**Comment by ValentinS4t1qbit** [comment]
@dlyongemallo Should be good now :)

**Comment by dlyongemallo** [comment]
Thanks @ValentinS4t1qbit  for the contribution!

**Pull request merged**
